package com.attendance.controller;

import com.attendance.dto.*;
import com.attendance.entity.*;
import com.attendance.repository.*;
import com.attendance.security.JwtUtils;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.stream.Collectors;

@CrossOrigin(origins = "*", maxAge = 3600)
@RestController
@RequestMapping("/api/auth")
public class AuthController {
    @Autowired
    AuthenticationManager authenticationManager;

    @Autowired
    UserRepository userRepository;

    @Autowired
    TeacherRepository teacherRepository;

    @Autowired
    StudentRepository studentRepository;

    @Autowired
    PasswordEncoder encoder;

    @Autowired
    JwtUtils jwtUtils;

    @PostMapping("/signin")
    public ResponseEntity<?> authenticateUser(@Valid @RequestBody LoginRequest loginRequest) {

        Authentication authentication = authenticationManager.authenticate(
                new UsernamePasswordAuthenticationToken(loginRequest.getEmail(), loginRequest.getPassword()));

        SecurityContextHolder.getContext().setAuthentication(authentication);
        String jwt = jwtUtils.generateJwtToken(authentication);

        UserDetails userDetails = (UserDetails) authentication.getPrincipal();
        List<String> roles = userDetails.getAuthorities().stream()
                .map(item -> item.getAuthority())
                .collect(Collectors.toList());

        User user = userRepository.findByEmail(userDetails.getUsername()).get();
        
        String studentStatus = null;
        Boolean teacherActive = null;

        if (user.getRole() == Role.STUDENT) {
            Student student = studentRepository.findByUser(user).get();
            studentStatus = student.isApproved() ? "APPROVED" : "PENDING";
            if (!student.isApproved()) {
                return ResponseEntity.badRequest().body(new MessageResponse("Your account is pending approval from a teacher."));
            }
        } else if (user.getRole() == Role.TEACHER) {
            Teacher teacher = teacherRepository.findByUser(user).get();
            teacherActive = teacher.isActive();
            if (!teacher.isActive()) {
                return ResponseEntity.badRequest().body(new MessageResponse("Your teacher account is deactivated by Admin."));
            }
        }

        return ResponseEntity.ok(new JwtResponse(jwt,
                user.getId(),
                user.getName(),
                user.getEmail(),
                roles,
                studentStatus,
                teacherActive));
    }

    @PostMapping("/signup")
    public ResponseEntity<?> registerUser(@Valid @RequestBody SignupRequest signUpRequest) {
        if (userRepository.findByEmail(signUpRequest.getEmail()).isPresent()) {
            return ResponseEntity.badRequest().body(new MessageResponse("Error: Email is already in use!"));
        }

        Role role = Role.valueOf(signUpRequest.getRole().toUpperCase());

        // Create new user's account
        User user = User.builder()
                .name(signUpRequest.getName())
                .email(signUpRequest.getEmail())
                .password(encoder.encode(signUpRequest.getPassword()))
                .role(role)
                .build();

        userRepository.save(user);

        if (role == Role.TEACHER) {
            // Verify Access Key
            if (signUpRequest.getAccessKey() == null) {
                 return ResponseEntity.badRequest().body(new MessageResponse("Error: Teacher Access Key is required!"));
            }
            
            // In a real app, Admin would have pre-shared this key. 
            // For this app, we check if it matches the generated keys list or a logic.
            // The prompt says "Generate unique Access Key for each teacher".
            // For registration, we'll check if the key is valid (could be hardcoded for first user or checked against a table).
            // Let's assume some keys are pre-generated by admin and stored.
            
            Teacher teacher = Teacher.builder()
                    .user(user)
                    .accessKey(signUpRequest.getAccessKey())
                    .isActive(true) // Start as active
                    .build();
            teacherRepository.save(teacher);
            
        } else if (role == Role.STUDENT) {
            if (signUpRequest.getVtuNo() == null) {
                 return ResponseEntity.badRequest().body(new MessageResponse("Error: VTU Number is required!"));
            }
            
            Student student = Student.builder()
                    .user(user)
                    .vtuNo(signUpRequest.getVtuNo())
                    .branch(signUpRequest.getBranch())
                    .semester(signUpRequest.getSemester())
                    .isApproved(false) // Wait for teacher approval
                    .build();
            studentRepository.save(student);
        }

        return ResponseEntity.ok(new MessageResponse("User registered successfully!"));
    }
}
